# Generated by Django 5.0 on 2023-12-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("report_media_id", models.CharField(max_length=255)),
                ("meshes_metadata", models.TextField()),
                ("original_report", models.TextField()),
                ("simplified_reports", models.TextField()),
                ("processing_status", models.TextField()),
            ],
        ),
    ]
