# Generated by Django 5.0 on 2023-12-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio_reports_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_metadata',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
    ]
